---
- name: install crontab
  ansible.builtin.package:
    name: cronie
    state: present


- name: Ensure that postgresql is started
  ansible.builtin.service:
    name: crond
    state: started

- name: Ensure a job that runs at 2 and 5 exists. Creates an entry like "0 5,2 * * ls -alh > /dev/null"
  ansible.builtin.cron:
    name: "reboot"
    minute: "0"
    hour: "5,2"
    job: "@midnight shutdown -r now"












